Super-Hero/Models/ErrorViewModel.cs
using System;

namespace Super_Hero.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Super-Hero/Models/Suit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Super_Hero.Models
{
    public class Suit
    {
        [Key]
        public int Id { get; set; }
        public string SuitNumber { get; set; }
        public string SuitName { get; set; }
        public string Specialty { get; set; }

    }
}

Super-Hero/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Super_Hero.Models;

namespace Super_Hero.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Super-Hero/Controllers/SuitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Super_Hero.Data;
using Super_Hero.Models;

namespace Super_Hero.Controllers
{
    public class SuitsController : Controller
    {
        private ApplicationDbContext db;

        public SuitsController(ApplicationDbContext db)
        {
            this.db = db;
        }

        // GET: Suits
        public ActionResult Index()
        {
            var Suits = db.Suits;
            return View(Suits);
        }

        // GET: Suits/Details/5
        public ActionResult Details(int id)
        {
            Suit suit = db.Suits.Find(id);
            return View(suit);
        }

        // GET: Suits/Create
        public ActionResult Create()
        {
            Suit suit = new Suit();
            return View();
        }

        // POST: Suits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind ("Id,SuitNumber,SuitName,Specialty")]Suit suit)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    db.Suits.Add(suit);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Suits/Edit/5
        public ActionResult Edit(int id)
        {
            return View(db.Suits.Find(id));
        }

        // POST: Suits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Suit suit)
        {
            try
            {
                // TODO: Add update logic here
                Suit editSuit = db.Suits.Find(id);
                editSuit.SuitNumber = suit.SuitNumber;
                editSuit.SuitName = suit.SuitName;
                editSuit.Specialty = suit.Specialty;
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Suits/Delete/5
        public ActionResult Delete(int id)
        {
            
            return View(db.Suits.Find(id));
        }

        // POST: Suits/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Suit suit)
        {
            try
            {
                // TODO: Add delete logic here
                Suit suitToRemove = db.Suits.Find(id); //?
                db.Suits.Remove(suitToRemove); //?
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Super-Hero/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


    <body class="body">
        <div class="text-center">
            <h1 class="display-4">Welcome</h1>
            <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        </div>
    </body>

Super-Hero/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super_Hero</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Iron Man</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suits" asp-action="Index">Suits</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Super_Hero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Super-Hero/Views/Suits/Create.cshtml
@model Super_Hero.Models.Suit

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Suit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SuitNumber" class="control-label"></label>
                <input asp-for="SuitNumber" class="form-control" />
                <span asp-validation-for="SuitNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuitName" class="control-label"></label>
                <input asp-for="SuitName" class="form-control" />
                <span asp-validation-for="SuitName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialty" class="control-label"></label>
                <input asp-for="Specialty" class="form-control" />
                <span asp-validation-for="Specialty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Super-Hero/Views/Suits/Delete.cshtml
@model Super_Hero.Models.Suit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Suit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuitNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuitNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuitName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuitName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialty)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Super-Hero/Views/Suits/Details.cshtml
@model Super_Hero.Models.Suit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Suit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuitNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuitNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuitName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuitName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialty)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Super-Hero/Views/Suits/Edit.cshtml
@model Super_Hero.Models.Suit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Suit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SuitNumber" class="control-label"></label>
                <input asp-for="SuitNumber" class="form-control" />
                <span asp-validation-for="SuitNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuitName" class="control-label"></label>
                <input asp-for="SuitName" class="form-control" />
                <span asp-validation-for="SuitName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialty" class="control-label"></label>
                <input asp-for="Specialty" class="form-control" />
                <span asp-validation-for="Specialty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Super-Hero/Views/Suits/index.cshtml
@model IEnumerable<Super_Hero.Models.Suit>

@{
    ViewData["Title"] = "index";
}

<h1>index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SuitNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuitName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SuitNumber)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.SuitName)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialty)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>